In [320]:
from sklearn import metrics
from sklearn.metrics import classification_report

In [321]:
import os
from tqdm import tqdm
train_dir = 'D:/KAES/Green/train'

# Setup empty lists to fill
labels_train = []
texts_train = []

# First go through the negatives, then through the positives
for label_type in ['neg', 'pos']:
    # Get the sub path
    dir_name = os.path.join(train_dir, label_type)
    print('loading ',label_type)
    # Loop over all files in path
    for fname in tqdm(os.listdir(dir_name)):
        
        # Only consider text files
        if fname[-4:] == '.txt':
            # Read the text file and put it in the list
            f = open(os.path.join(dir_name, fname),encoding="utf-8")
            name=os.path.splitext(f.name)[0]
            texts_train.append(f.read())
            labels_train.append(name[-1])
            f.close()
          

 15%|███████████▍                                                               | 1963/12822 [00:00<00:01, 9829.24it/s]

loading  neg


 16%|████████████                                                              | 2034/12500 [00:00<00:01, 10049.49it/s]

loading  pos


100%|██████████████████████████████████████████████████████████████████████████| 12500/12500 [00:01<00:00, 9740.60it/s]


In [322]:
import os

test_dir = 'D:/KAES/Green/test'

# Setup empty lists to fill
labels_test = []
texts_test = []

# First go through the negatives, then through the positives
for label_type in ['neg', 'pos']:
    # Get the sub path
    dir_name = os.path.join(test_dir, label_type)
    print('loading ',label_type)
    # Loop over all files in path
    for fname in tqdm(os.listdir(dir_name)):
        
        # Only consider text files
        if fname[-4:] == '.txt':
            # Read the text file and put it in the list
            f = open(os.path.join(dir_name, fname),encoding="utf-8")
            name=os.path.splitext(f.name)[0]
            texts_test.append(f.read())
            labels_test.append(name[-1])
            f.close()

  8%|██████                                                                      | 998/12500 [00:00<00:01, 9977.68it/s]

loading  neg


  8%|█████▉                                                                      | 975/12500 [00:00<00:01, 9747.75it/s]

loading  pos


100%|██████████████████████████████████████████████████████████████████████████| 12500/12500 [00:01<00:00, 9887.01it/s]


In [323]:
for i, element in enumerate(texts_train):
    element = element.replace('<br />','')
    texts_train[i] = element

In [324]:
for i, element in enumerate(texts_test):
    element = element.replace('<br />','')
    texts_test[i] = element

In [325]:
import pandas as pd
df = pd.DataFrame(texts_train, columns =['reviews'])
df1=pd.DataFrame(labels_train, columns =['labels'])
dataframe_train=pd.concat([df,df1], axis=1)

In [326]:
import pandas as pd
df = pd.DataFrame(texts_test, columns =['reviews'])
df1=pd.DataFrame(labels_test, columns =['labels'])
dataframe_test=pd.concat([df,df1], axis=1)

In [327]:
dataframe_train

reviews labels
0      Story of a man who has unnatural feelings for ...      3
1      Airport '77 starts as a brand new luxury 747 p...      4
2      This film lacked something I couldn't put my f...      4
3      Sorry everyone,,, I know this is supposed to b...      1
4      When I was little my parents took me along to ...      1
...                                                  ...    ...
25317  Seeing as the vote average was pretty low, and...      9
25318  The plot had some wretched, unbelievable twist...      8
25319  I am amazed at how this movie(and most others ...      0
25320  A Christmas Together actually came before my t...      8
25321  Working-class romantic drama from director Mar...      7

[25322 rows x 2 columns]

In [328]:
dataframe_test

reviews labels
0      Once again Mr. Costner has dragged out a movie...      2
1      This is an example of why the majority of acti...      4
2      First of all I hate those moronic rappers, who...      1
3      Not even the Beatles could write songs everyon...      3
4      Brass pictures (movies is not a fitting word f...      3
...                                                  ...    ...
24995  I was extraordinarily impressed by this film. ...      8
24996  Although I'm not a golf fan, I attended a snea...      0
24997  From the start of "The Edge Of Love", the view...      8
24998  This movie, with all its complexity and subtle...      0
24999  I've seen this story before but my kids haven'...      7

[25000 rows x 2 columns]

In [329]:
dataframe_train.labels = pd.to_numeric(dataframe_train.labels, errors='coerce')
dataframe_test.labels = pd.to_numeric(dataframe_test.labels, errors='coerce')
dataframe_train.labels.loc[dataframe_train['labels'] == 0.0] = 10.0
dataframe_test.labels.loc[dataframe_test['labels'] == 0.0] = 10.0

D:\Anaconda\envs\name_X\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
D:\Anaconda\envs\name_X\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [330]:
dataframe_train.labels.unique()

array([ 3.,  4.,  1.,  2., nan,  9.,  8., 10.,  7.])

In [331]:
dataframe_test.labels.unique()

array([ 2,  4,  1,  3, 10,  7,  9,  8], dtype=int64)

In [332]:
dataframe_train=dataframe_train.dropna()
dataframe_train=dataframe_train.drop_duplicates()

dataframe_test=dataframe_test.dropna()
dataframe_train=dataframe_test.drop_duplicates()

In [333]:
dataframe_train['binary'] = dataframe_train['labels'].apply(binary)
dataframe_train.head(2)

dataframe_test['binary'] = dataframe_test['labels'].apply(binary)
dataframe_train.head(2)

<ipython-input-333-992619e1fa51>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['binary'] = dataframe_train['labels'].apply(binary)


reviews  labels  binary
0  Once again Mr. Costner has dragged out a movie...       2       0
1  This is an example of why the majority of acti...       4       0

In [334]:
from textblob import TextBlob
def polarity_txt(text):
    return TextBlob(text).sentiment[0]

In [335]:
def subj_txt(text):
    return  TextBlob(text).sentiment[1]

In [336]:
def len_txt(text):
    return len(text)

In [337]:
dataframe_train['lenght'] = dataframe_train['reviews'].apply(len_txt)
dataframe_train.head(2)

<ipython-input-337-b8acc4d380b9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['lenght'] = dataframe_train['reviews'].apply(len_txt)


reviews  labels  binary  lenght
0  Once again Mr. Costner has dragged out a movie...       2       0     900
1  This is an example of why the majority of acti...       4       0    1311

In [338]:
dataframe_test['lenght'] = dataframe_test['reviews'].apply(len_txt)
dataframe_test.head(2)

reviews  labels  binary  lenght
0  Once again Mr. Costner has dragged out a movie...       2       0     900
1  This is an example of why the majority of acti...       4       0    1311

In [339]:
dataframe_train['polarity'] = dataframe_train['reviews'].apply(polarity_txt)
dataframe_train.head(2)

<ipython-input-339-da82943f9506>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['polarity'] = dataframe_train['reviews'].apply(polarity_txt)


reviews  labels  binary  lenght  \
0  Once again Mr. Costner has dragged out a movie...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   

   polarity  
0  0.063860  
1  0.042554

In [340]:
dataframe_test['polarity'] = dataframe_test['reviews'].apply(polarity_txt)
dataframe_test.head(2)

reviews  labels  binary  lenght  \
0  Once again Mr. Costner has dragged out a movie...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   

   polarity  
0  0.063860  
1  0.042554

In [341]:
dataframe_train['subjectivity'] = dataframe_train['reviews'].apply(subj_txt)
dataframe_train.head(2)

<ipython-input-341-564aa01c1594>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['subjectivity'] = dataframe_train['reviews'].apply(subj_txt)


reviews  labels  binary  lenght  \
0  Once again Mr. Costner has dragged out a movie...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   

   polarity  subjectivity  
0  0.063860      0.562982  
1  0.042554      0.387165

In [342]:
dataframe_test['subjectivity'] = dataframe_test['reviews'].apply(subj_txt)
dataframe_test.head(2)

reviews  labels  binary  lenght  \
0  Once again Mr. Costner has dragged out a movie...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   

   polarity  subjectivity  
0  0.063860      0.562982  
1  0.042554      0.387165

In [343]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [344]:
def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return round(count/(len(text) - text.count(" ")), 3)

dataframe_train['punct%'] =  dataframe_train['reviews'].apply(lambda x: count_punct(x))

dataframe_test['punct%'] =  dataframe_test['reviews'].apply(lambda x: count_punct(x))

<ipython-input-344-68b6e56549c9>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['punct%'] =  dataframe_train['reviews'].apply(lambda x: count_punct(x))


In [345]:
def remove_punct(text):
    text_nopunct = "".join([char for char in text if char not in string.punctuation])
    return text_nopunct

dataframe_train['reviews'] = dataframe_train['reviews'].apply(lambda x: remove_punct(x))
dataframe_test['reviews'] = dataframe_test['reviews'].apply(lambda x: remove_punct(x))
dataframe_train.head()

<ipython-input-345-b18fe4d28107>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['reviews'] = dataframe_train['reviews'].apply(lambda x: remove_punct(x))


reviews  labels  binary  lenght  \
0  Once again Mr Costner has dragged out a movie ...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   
2  First of all I hate those moronic rappers who ...       1       0    1212   
3  Not even the Beatles could write songs everyon...       3       0    1673   
4  Brass pictures movies is not a fitting word fo...       3       0    1449   

   polarity  subjectivity  punct%  
0  0.063860      0.562982   0.027  
1  0.042554      0.387165   0.040  
2  0.000569      0.554710   0.025  
3  0.052206      0.407353   0.029  
4  0.086952      0.412810   0.030

In [346]:
import re

# Function to Tokenize words
def tokenize(text):
    tokens = re.split('\W+', text) 
    return tokens

dataframe_train['reviews_tok'] = dataframe_train['reviews'].apply(lambda x: tokenize(x.lower())) 
 
dataframe_test['reviews_tok'] = dataframe_test['reviews'].apply(lambda x: tokenize(x.lower())) 

dataframe_train.head()

<ipython-input-346-796a30a9f4d5>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['reviews_tok'] = dataframe_train['reviews'].apply(lambda x: tokenize(x.lower()))


reviews  labels  binary  lenght  \
0  Once again Mr Costner has dragged out a movie ...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   
2  First of all I hate those moronic rappers who ...       1       0    1212   
3  Not even the Beatles could write songs everyon...       3       0    1673   
4  Brass pictures movies is not a fitting word fo...       3       0    1449   

   polarity  subjectivity  punct%  \
0  0.063860      0.562982   0.027   
1  0.042554      0.387165   0.040   
2  0.000569      0.554710   0.025   
3  0.052206      0.407353   0.029   
4  0.086952      0.412810   0.030   

                                         reviews_tok  
0  [once, again, mr, costner, has, dragged, out, ...  
1  [this, is, an, example, of, why, the, majority...  
2  [first, of, all, i, hate, those, moronic, rapp...  
3  [not, even, the, beatles, could, write, songs,...  
4  [brass, pictures, movies, is, not, a, fitting,...

In [347]:
import nltk

stopword = nltk.corpus.stopwords.words('english')# All English Stopwords


In [348]:

# Function to remove Stopwords
def remove_stopwords(tokenized_list):
    text = [word for word in tokenized_list if word not in stopword]# To remove all stopwords
    return text

dataframe_train['reviews_tok'] = dataframe_train['reviews_tok'].apply(lambda x: remove_stopwords(x))
dataframe_test['reviews_tok'] = dataframe_test['reviews_tok'].apply(lambda x: remove_stopwords(x))
dataframe_train.head()

<ipython-input-348-19e13010008d>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['reviews_tok'] = dataframe_train['reviews_tok'].apply(lambda x: remove_stopwords(x))


reviews  labels  binary  lenght  \
0  Once again Mr Costner has dragged out a movie ...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   
2  First of all I hate those moronic rappers who ...       1       0    1212   
3  Not even the Beatles could write songs everyon...       3       0    1673   
4  Brass pictures movies is not a fitting word fo...       3       0    1449   

   polarity  subjectivity  punct%  \
0  0.063860      0.562982   0.027   
1  0.042554      0.387165   0.040   
2  0.000569      0.554710   0.025   
3  0.052206      0.407353   0.029   
4  0.086952      0.412810   0.030   

                                         reviews_tok  
0  [mr, costner, dragged, movie, far, longer, nec...  
1  [example, majority, action, films, generic, bo...  
2  [first, hate, moronic, rappers, couldnt, act, ...  
3  [even, beatles, could, write, songs, everyone,...  
4  [brass, pictures, movies, fitting, word, reall...

In [349]:
ps = nltk.PorterStemmer()

def stemming(tokenized_text):
    text = [ps.stem(word) for word in tokenized_text]
    return text

dataframe_train['reviews_tok'] = dataframe_train['reviews_tok'].apply(lambda x: stemming(x))

dataframe_test['reviews_tok'] = dataframe_test['reviews_tok'].apply(lambda x: stemming(x))

dataframe_train.head()

<ipython-input-349-3ec6c611c911>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_train['reviews_tok'] = dataframe_train['reviews_tok'].apply(lambda x: stemming(x))


reviews  labels  binary  lenght  \
0  Once again Mr Costner has dragged out a movie ...       2       0     900   
1  This is an example of why the majority of acti...       4       0    1311   
2  First of all I hate those moronic rappers who ...       1       0    1212   
3  Not even the Beatles could write songs everyon...       3       0    1673   
4  Brass pictures movies is not a fitting word fo...       3       0    1449   

   polarity  subjectivity  punct%  \
0  0.063860      0.562982   0.027   
1  0.042554      0.387165   0.040   
2  0.000569      0.554710   0.025   
3  0.052206      0.407353   0.029   
4  0.086952      0.412810   0.030   

                                         reviews_tok  
0  [mr, costner, drag, movi, far, longer, necessa...  
1  [exampl, major, action, film, gener, bore, the...  
2  [first, hate, moron, rapper, couldnt, act, gun...  
3  [even, beatl, could, write, song, everyon, lik...  
4  [brass, pictur, movi, fit, word, realli, somew...

In [350]:
dataframe_train

reviews  labels  binary  \
0      Once again Mr Costner has dragged out a movie ...       2       0   
1      This is an example of why the majority of acti...       4       0   
2      First of all I hate those moronic rappers who ...       1       0   
3      Not even the Beatles could write songs everyon...       3       0   
4      Brass pictures movies is not a fitting word fo...       3       0   
...                                                  ...     ...     ...   
24995  I was extraordinarily impressed by this film I...       8       1   
24996  Although Im not a golf fan I attended a sneak ...      10       0   
24997  From the start of The Edge Of Love the viewer ...       8       1   
24998  This movie with all its complexity and subtlet...      10       0   
24999  Ive seen this story before but my kids havent ...       7       1   

       lenght  polarity  subjectivity  punct%  \
0         900  0.063860      0.562982   0.027   
1        1311  0.042554      0.387165   0.040   
2        1212  0.000569      0.554710   0.025   
3        1673  0.052206      0.407353   0.029   
4        1449  0.086952      0.412810   0.030   
...       ...       ...           ...     ...   
24995     679  0.456667      0.605556   0.030   
24996     659  0.098039      0.605882   0.033   
24997    3963  0.244534      0.494915   0.041   
24998     905  0.246374      0.594210   0.037   
24999    1235 -0.022123      0.529167   0.023   

                                             reviews_tok  
0      [mr, costner, drag, movi, far, longer, necessa...  
1      [exampl, major, action, film, gener, bore, the...  
2      [first, hate, moron, rapper, couldnt, act, gun...  
3      [even, beatl, could, write, song, everyon, lik...  
4      [brass, pictur, movi, fit, word, realli, somew...  
...                                                  ...  
24995  [extraordinarili, impress, film, one, best, sp...  
24996  [although, im, golf, fan, attend, sneak, previ...  
24997  [start, edg, love, viewer, transport, strike, ...  
24998  [movi, complex, subtleti, make, one, thoughtpr...  
24999  [ive, seen, stori, kid, havent, boy, troubl, p...  

[24804 rows x 8 columns]

In [351]:
dataframe_test

reviews  labels  binary  \
0      Once again Mr Costner has dragged out a movie ...       2       0   
1      This is an example of why the majority of acti...       4       0   
2      First of all I hate those moronic rappers who ...       1       0   
3      Not even the Beatles could write songs everyon...       3       0   
4      Brass pictures movies is not a fitting word fo...       3       0   
...                                                  ...     ...     ...   
24995  I was extraordinarily impressed by this film I...       8       1   
24996  Although Im not a golf fan I attended a sneak ...      10       0   
24997  From the start of The Edge Of Love the viewer ...       8       1   
24998  This movie with all its complexity and subtlet...      10       0   
24999  Ive seen this story before but my kids havent ...       7       1   

       lenght  polarity  subjectivity  punct%  \
0         900  0.063860      0.562982   0.027   
1        1311  0.042554      0.387165   0.040   
2        1212  0.000569      0.554710   0.025   
3        1673  0.052206      0.407353   0.029   
4        1449  0.086952      0.412810   0.030   
...       ...       ...           ...     ...   
24995     679  0.456667      0.605556   0.030   
24996     659  0.098039      0.605882   0.033   
24997    3963  0.244534      0.494915   0.041   
24998     905  0.246374      0.594210   0.037   
24999    1235 -0.022123      0.529167   0.023   

                                             reviews_tok  
0      [mr, costner, drag, movi, far, longer, necessa...  
1      [exampl, major, action, film, gener, bore, the...  
2      [first, hate, moron, rapper, couldnt, act, gun...  
3      [even, beatl, could, write, song, everyon, lik...  
4      [brass, pictur, movi, fit, word, realli, somew...  
...                                                  ...  
24995  [extraordinarili, impress, film, one, best, sp...  
24996  [although, im, golf, fan, attend, sneak, previ...  
24997  [start, edg, love, viewer, transport, strike, ...  
24998  [movi, complex, subtleti, make, one, thoughtpr...  
24999  [ive, seen, stori, kid, havent, boy, troubl, p...  

[25000 rows x 8 columns]

In [352]:
dataframe_train['labels'].value_counts()

10    4966
1     4948
8     2842
4     2619
3     2514
9     2339
7     2296
2     2280
Name: labels, dtype: int64

In [353]:
dataframe_test['labels'].value_counts()

1     5022
10    4999
8     2850
4     2635
3     2541
9     2344
7     2307
2     2302
Name: labels, dtype: int64

In [354]:
dataframe_train.lenght=dataframe_train.lenght/dataframe_train.lenght.max()

D:\Anaconda\envs\name_X\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [355]:
dataframe_test.lenght=dataframe_test.lenght/dataframe_test.lenght.max()

In [356]:
import nltk
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [lemmatizer.lemmatize(word) for word in tokens if word not in stopword]
    return str(text)

In [357]:


x_train = dataframe_train[['reviews','polarity', 'subjectivity','lenght','punct%','binary']]
x_test = dataframe_test[['reviews','polarity', 'subjectivity','lenght','punct%','binary']]
y_train=dataframe_train.labels
y_test=dataframe_test.labels




In [358]:
x_train

reviews  polarity  \
0      Once again Mr Costner has dragged out a movie ...  0.063860   
1      This is an example of why the majority of acti...  0.042554   
2      First of all I hate those moronic rappers who ...  0.000569   
3      Not even the Beatles could write songs everyon...  0.052206   
4      Brass pictures movies is not a fitting word fo...  0.086952   
...                                                  ...       ...   
24995  I was extraordinarily impressed by this film I...  0.456667   
24996  Although Im not a golf fan I attended a sneak ...  0.098039   
24997  From the start of The Edge Of Love the viewer ...  0.244534   
24998  This movie with all its complexity and subtlet...  0.246374   
24999  Ive seen this story before but my kids havent ... -0.022123   

       subjectivity    lenght  punct%  binary  
0          0.562982  0.070922   0.027       0  
1          0.387165  0.103310   0.040       0  
2          0.554710  0.095508   0.025       0  
3          0.407353  0.131836   0.029       0  
4          0.412810  0.114184   0.030       0  
...             ...       ...     ...     ...  
24995      0.605556  0.053507   0.030       1  
24996      0.605882  0.051931   0.033       0  
24997      0.494915  0.312293   0.041       1  
24998      0.594210  0.071316   0.037       0  
24999      0.529167  0.097321   0.023       1  

[24804 rows x 6 columns]

In [359]:
x_test

reviews  polarity  \
0      Once again Mr Costner has dragged out a movie ...  0.063860   
1      This is an example of why the majority of acti...  0.042554   
2      First of all I hate those moronic rappers who ...  0.000569   
3      Not even the Beatles could write songs everyon...  0.052206   
4      Brass pictures movies is not a fitting word fo...  0.086952   
...                                                  ...       ...   
24995  I was extraordinarily impressed by this film I...  0.456667   
24996  Although Im not a golf fan I attended a sneak ...  0.098039   
24997  From the start of The Edge Of Love the viewer ...  0.244534   
24998  This movie with all its complexity and subtlet...  0.246374   
24999  Ive seen this story before but my kids havent ... -0.022123   

       subjectivity    lenght  punct%  binary  
0          0.562982  0.070922   0.027       0  
1          0.387165  0.103310   0.040       0  
2          0.554710  0.095508   0.025       0  
3          0.407353  0.131836   0.029       0  
4          0.412810  0.114184   0.030       0  
...             ...       ...     ...     ...  
24995      0.605556  0.053507   0.030       1  
24996      0.605882  0.051931   0.033       0  
24997      0.494915  0.312293   0.041       1  
24998      0.594210  0.071316   0.037       0  
24999      0.529167  0.097321   0.023       1  

[25000 rows x 6 columns]

In [360]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import FeatureUnion
from sklearn.feature_extraction import DictVectorizer
class ItemSelector(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, data_dict):
        return data_dict[self.key]


class TextStats(BaseEstimator, TransformerMixin):
    """Extract features from each document for DictVectorizer"""

    def fit(self, x, y=None):
        return self

    def transform(self, data):
        return [{'pos':  row['polarity'], 'sub': row['subjectivity'],'lenght': row['lenght'],'punct%': row['punct%'],'binary': row['binary']} for _, row in data.iterrows()]

In [361]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer


pipeline = Pipeline([
    ('union', FeatureUnion(
        transformer_list=[

            # Pipeline for pulling features from the text
            ('reviews', Pipeline([
                ('selector', ItemSelector(key='reviews')),
                ('tfidf', TfidfVectorizer(preprocessor=clean_text,
                     use_idf=1,smooth_idf=1)),
            ])),

            # Pipeline for pulling metadata features
            ('stats', Pipeline([
                ('selector', ItemSelector(key=['polarity', 'subjectivity', 'lenght','punct%','binary'])),
                ('stats', TextStats()),  # returns a list of dicts
                ('vect', DictVectorizer()),  # list of dicts -> feature matrix
            ])),

        ],

       
    ))
])

In [362]:

pipeline.fit(x_train)

Pipeline(steps=[('union',
                 FeatureUnion(transformer_list=[('reviews',
                                                 Pipeline(steps=[('selector',
                                                                  ItemSelector(key='reviews')),
                                                                 ('tfidf',
                                                                  TfidfVectorizer(preprocessor=<function clean_text at 0x000001F609B8D4C0>,
                                                                                  smooth_idf=1,
                                                                                  use_idf=1))])),
                                                ('stats',
                                                 Pipeline(steps=[('selector',
                                                                  ItemSelector(key=['polarity',
                                                                                    'subjectivity',

In [363]:
train_vec = pipeline.transform(x_train)
test_vec = pipeline.transform(x_test)

In [364]:
from sklearn.linear_model import LogisticRegression

import time
startTime = time.time() # время начала замера

clf = LogisticRegression()
clf.fit(train_vec, y_train)

endTime = time.time() #время конца замера
totalTime = endTime - startTime #вычисляем затраченное время

print("Время, затраченное на выполнение данного кода = ", totalTime)

Время, затраченное на выполнение данного кода =  25.201635360717773


D:\Anaconda\envs\name_X\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [365]:
from sklearn.metrics import classification_report
report = classification_report(y_test, clf.predict(test_vec))
print(report)

              precision    recall  f1-score   support

           1       0.72      0.94      0.81      5022
           2       0.93      0.46      0.61      2302
           3       0.90      0.64      0.75      2541
           4       0.84      0.75      0.79      2635
           7       0.91      0.87      0.89      2307
           8       0.88      0.94      0.91      2850
           9       0.90      0.87      0.89      2344
          10       0.85      0.97      0.91      4999

    accuracy                           0.84     25000
   macro avg       0.87      0.80      0.82     25000
weighted avg       0.85      0.84      0.83     25000



In [123]:
startTime = time.time() # время начала замера


from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=200,n_jobs=-1,class_weight='balanced')
clf.fit(train_vec, y_train)
print(metrics.accuracy_score(y_test, clf.predict(test_vec)))


endTime = time.time() #время конца замера
totalTime = endTime - startTime #вычисляем затраченное время

print("Время, затраченное на выполнение данного кода = ", totalTime)

0.37512
Время, затраченное на выполнение данного кода =  35.01049876213074


In [569]:
pip install xgboost


Note: you may need to restart the kernel to use updated packages.Collecting xgboost



In [366]:
from xgboost import XGBClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = make_pipeline(StandardScaler(with_mean=False),  XGBClassifier(eval_metric='merror',nthread=16))

clf.fit(train_vec, y_train)


D:\Anaconda\envs\name_X\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('xgbclassifier',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, eval_metric='merror',
                               gamma=0, gpu_id=-1, importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=16, nthread=16, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                            

In [367]:
print(metrics.accuracy_score(y_test, clf.predict(test_vec)))
report = classification_report(y_test, clf.predict(test_vec))
print(report)

0.90128
              precision    recall  f1-score   support

           1       0.81      0.95      0.87      5022
           2       0.98      0.70      0.82      2302
           3       0.96      0.76      0.84      2541
           4       0.92      0.83      0.87      2635
           7       0.98      0.94      0.96      2307
           8       0.93      0.98      0.95      2850
           9       0.96      0.94      0.95      2344
          10       0.88      0.98      0.93      4999

    accuracy                           0.90     25000
   macro avg       0.93      0.88      0.90     25000
weighted avg       0.91      0.90      0.90     25000



In [368]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier

clf_sv = LinearSVC( class_weight = 'balanced', multi_class='ovr',  max_iter=10000) #Support Vector machines
clf_sgd = SGDClassifier(max_iter=200,) # Stochastic Gradient Classifier

In [369]:
%%time
import numpy as np
from sklearn.model_selection import cross_val_score

clfs = [clf_sv, clf_sgd]
cv = 3
for clf in clfs:
    scores = cross_val_score(clf,train_vec, y_train, cv=cv, scoring="accuracy" )
    print (scores)
    print (("Mean score: {0:.3f} (+/-{1:.3f})").format(
        np.mean(scores), np.std(scores)))

[0.50120948 0.50096759 0.50580552]
Mean score: 0.503 (+/-0.002)
[0.52140784 0.51136913 0.52164973]
Mean score: 0.518 (+/-0.005)
Wall time: 7.97 s


In [202]:
clf_sgd.fit(train_vec, y_train )

SGDClassifier(max_iter=200)

In [203]:
from sklearn.metrics import classification_report
report = classification_report(y_test, clf_sgd.predict(test_vec))
print(report)

              precision    recall  f1-score   support

           0       0.80      0.98      0.88      4999
           1       0.70      0.93      0.80      5022
           2       0.95      0.49      0.64      2302
           3       0.98      0.63      0.77      2541
           4       0.97      0.69      0.81      2635
           7       0.91      0.91      0.91      2307
           8       0.95      0.86      0.90      2850
           9       0.84      0.95      0.89      2344

    accuracy                           0.84     25000
   macro avg       0.89      0.81      0.83     25000
weighted avg       0.86      0.84      0.83     25000



In [43]:
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

In [46]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.svm import SVC
svm_model = GridSearchCV(SVC(), params_grid, cv=5,n_jobs=-1)
svm_model.fit(train_vec, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}])

In [47]:
print('Best score for training data:', svm_model.best_score_,"\n") 

# View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model = svm_model.best_estimator_
y_pred = final_model.predict(test_vec)


Best score for training data: 0.39592 

Best C: 1 

Best Kernel: linear 

Best Gamma: scale 



In [51]:
# Making the Confusion Matrix

print(confusion_matrix(y_test,y_pred))
print("\n")
print(classification_report(y_test,y_pred))

print("Training set score for SVM: %f" % final_model.score(train_vec , y_train))
print("Testing  set score for SVM: %f" % final_model.score(test_vec , y_test ))

svm_model.score

[[3622  223   24   59  114  208  564  185]
 [ 248 3876  234  261  314   31   45   13]
 [ 146 1272  171  315  313   34   44    7]
 [ 180  944  201  400  615  113   80    8]
 [ 203  613  162  418  828  200  189   22]
 [ 573  107   26  118  299  542  551   91]
 [1153  107   29   81  189  432  693  166]
 [1304  104   14   39   93  199  451  140]]


              precision    recall  f1-score   support

           0       0.49      0.72      0.58      4999
           1       0.53      0.77      0.63      5022
           2       0.20      0.07      0.11      2302
           3       0.24      0.16      0.19      2541
           4       0.30      0.31      0.31      2635
           7       0.31      0.23      0.27      2307
           8       0.26      0.24      0.25      2850
           9       0.22      0.06      0.09      2344

    accuracy                           0.41     25000
   macro avg       0.32      0.32      0.30     25000
weighted avg       0.36      0.41      0.37     25000

Tr

<bound method BaseSearchCV.score of GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}])>

In [370]:
from sklearn.svm import SVC
svm_model=SVC(kernel='linear',class_weight='balanced')
svm_model.fit(train_vec,y_train)
y_pred = svm_model.predict(test_vec)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.92      0.84      0.88      5022
           2       0.81      0.89      0.85      2302
           3       0.85      0.90      0.87      2541
           4       0.88      0.90      0.89      2635
           7       0.92      0.95      0.93      2307
           8       0.95      0.90      0.92      2850
           9       0.91      0.94      0.93      2344
          10       0.96      0.95      0.96      4999

    accuracy                           0.91     25000
   macro avg       0.90      0.91      0.90     25000
weighted avg       0.91      0.91      0.91     25000



In [57]:
svm_model.score(test_vec , y_test )

0.37628

In [500]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = make_pipeline(StandardScaler(with_mean=False), SVC(kernel='linear',class_weight='balanced'))
clf.fit(train_vec,y_train)
y_pred = svm_model.predict(test_vec)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      0.55      0.56      4999
           1       0.63      0.61      0.62      5022
           2       0.22      0.22      0.22      2302
           3       0.24      0.25      0.25      2541
           4       0.30      0.33      0.31      2635
           7       0.31      0.34      0.32      2307
           8       0.28      0.26      0.27      2850
           9       0.23      0.23      0.23      2344

    accuracy                           0.39     25000
   macro avg       0.35      0.35      0.35     25000
weighted avg       0.40      0.39      0.40     25000



In [130]:
from sklearn.decomposition import TruncatedSVD
tsvd = TruncatedSVD(n_components=100)
x_train_pca = tsvd.fit_transform(train_vec)
x_test_pca = tsvd.transform(test_vec)

In [131]:
import time
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
startTime = time.time() # время начала замера

clf = LogisticRegression(max_iter=500,n_jobs=-1,class_weight='balanced')
clf.fit(x_train_pca, y_train)
print(metrics.accuracy_score(y_test, clf.predict(x_test_pca)))

endTime = time.time() #время конца замера
totalTime = endTime - startTime #вычисляем затраченное время

print("Время, затраченное на выполнение данного кода = ", totalTime)

0.37068
Время, затраченное на выполнение данного кода =  7.405126094818115


In [110]:
from xgboost import XGBClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = make_pipeline(StandardScaler(with_mean=False),  XGBClassifier(eval_metric='merror',nthread=16))

clf.fit(x_train_pca, y_train)

D:\Anaconda\envs\name_X\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('xgbclassifier',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, eval_metric='merror',
                               gamma=0, gpu_id=-1, importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=16, nthread=16, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                            

In [111]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,clf.predict(x_test_pca))

array([[3297,  320,   58,   74,  137,  219,  591,  303],
       [ 308, 3694,  280,  280,  286,   51,   90,   33],
       [ 159, 1216,  187,  277,  287,   66,   86,   24],
       [ 183,  971,  187,  388,  519,  150,  116,   27],
       [ 234,  658,  165,  366,  678,  246,  244,   44],
       [ 530,  166,   40,  112,  300,  468,  555,  136],
       [1070,  180,   40,   66,  215,  446,  639,  194],
       [1202,  141,   32,   54,  110,  220,  419,  166]], dtype=int64)

In [112]:
print(classification_report(y_test,clf.predict(x_test_pca)))

              precision    recall  f1-score   support

           0       0.47      0.66      0.55      4999
           1       0.50      0.74      0.60      5022
           2       0.19      0.08      0.11      2302
           3       0.24      0.15      0.19      2541
           4       0.27      0.26      0.26      2635
           7       0.25      0.20      0.22      2307
           8       0.23      0.22      0.23      2850
           9       0.18      0.07      0.10      2344

    accuracy                           0.38     25000
   macro avg       0.29      0.30      0.28     25000
weighted avg       0.33      0.38      0.34     25000

